name: shelf_hot_reload
description: Middleware for the shelf web server to allow html hot reload on file changes.
version: 0.1.0
homepage: https://github.com/fkettelhoit/shelf-hot-reload
author: Frederic Kettelhoit <kettelhoit@gmail.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  shelf: ^0.7.2
  shelf_web_socket: ^0.2.2+4
  vm_service_lib: ^3.14.2
  watcher: ^0.9.7+10

dev_dependencies:
  effective_dart: ^1.1.0
  test: ^1.6.0
